package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.WebDriverRunner;
import io.qameta.allure.Description;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;



import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.visible;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;


public class Leroy extends TestBase {

    @BeforeEach
    public void ClosePopup(){
        step("Открыть https://leroymerlin.ru/", () -> {
            open("https://leroymerlin.ru/");
        });
    }


    @Test
    @Description("Тест на главной странице Леруа")
    @DisplayName("Проверка отображения главного баннера")
    void checkMainBanner() {
        step("Проверить отображение баннера", () -> {
            $("#tns1-mw").shouldBe(visible);
        });
    }

    @Test
    @Description("Тест на главной странице Леруа")
    @DisplayName("Проверка отображения второго баннера")
    void checkMenu() {
        step("Проверить отображение баннера", () -> {
            $("#tns2-mw").shouldBe(visible);
        });
    }

    @Test
    @Description("Тест главной страницы Леруа")
    @DisplayName("Проверка перехода в корзину")
    void checkGoToCart() {
        step("Кликнуть на корзину", () -> {
            $x("//a[@slot=\"basket\"]").click();
        });

        step("Проверить url", () -> {
            String urlPage = WebDriverRunner.url();
            assertEquals(urlPage, "https://leroymerlin.ru/basket/");
        });
    }

    @Test
    @Description("Тест главной страницы Леруа")
    @DisplayName("Проверка перехода к магазинам")
    void checkGoToSearch() {
        step("Кликнуть Магазины", () -> {
            $x("(//a[@slot=\"shops\"])[2]").click();
        });

        step("Проверить url", () -> {
            String urlPage = WebDriverRunner.url();
            assertEquals(urlPage, "https://leroymerlin.ru/shop/");
        });
    }

    @Test
    @Description("Тест главной страницы Леруа")
    @DisplayName("Проверка отображения промо баннера")
    void checkGoToLogin() {
        step("Проверить наличие промо баннера", () -> {
            $x("//div[@class=\"promo-banners\"]").shouldBe(visible);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Page title should have text 'HTTP 403'", () -> {
            String expectedTitle = "HTTP 403";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}